version: "3"

# Config file for compose, a tool that allows for easily managing multiple docker containers.
# https://docs.docker.com/compose/

services:
    redis:
        container_name: meteoredis
        image: redis/redis-stack
        ports:
            - 6379:6379
        restart: unless-stopped
        volumes:
            - ./data/redis:/data

    mongo:
        image: mongo
        ports:
            - 27017:27017
        restart: unless-stopped
        volumes:
            - ./data/mongo:/data/db
        environment:
            MONGO_INITDB_DATABASE: meteoritedb
            MONGO_INITDB_ROOT_USERNAME: server
            MONGO_INITDB_ROOT_PASSWORD: password
